package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FormationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormationAllPropertiesEquals(Formation expected, Formation actual) {
        assertFormationAutoGeneratedPropertiesEquals(expected, actual);
        assertFormationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormationAllUpdatablePropertiesEquals(Formation expected, Formation actual) {
        assertFormationUpdatableFieldsEquals(expected, actual);
        assertFormationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormationAutoGeneratedPropertiesEquals(Formation expected, Formation actual) {
        assertThat(expected)
            .as("Verify Formation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormationUpdatableFieldsEquals(Formation expected, Formation actual) {
        assertThat(expected)
            .as("Verify Formation relevant properties")
            .satisfies(e -> assertThat(e.getNomFormation()).as("check nomFormation").isEqualTo(actual.getNomFormation()))
            .satisfies(e -> assertThat(e.getImageFormation()).as("check imageFormation").isEqualTo(actual.getImageFormation()))
            .satisfies(
                e ->
                    assertThat(e.getImageFormationContentType())
                        .as("check imageFormation contenty type")
                        .isEqualTo(actual.getImageFormationContentType())
            )
            .satisfies(e -> assertThat(e.getTypeFormation()).as("check typeFormation").isEqualTo(actual.getTypeFormation()))
            .satisfies(e -> assertThat(e.getDuree()).as("check duree").isEqualTo(actual.getDuree()))
            .satisfies(e -> assertThat(e.getAdmission()).as("check admission").isEqualTo(actual.getAdmission()))
            .satisfies(e -> assertThat(e.getDiplomeRequis()).as("check diplomeRequis").isEqualTo(actual.getDiplomeRequis()))
            .satisfies(e -> assertThat(e.getFicheFormation()).as("check ficheFormation").isEqualTo(actual.getFicheFormation()))
            .satisfies(
                e ->
                    assertThat(e.getFicheFormationContentType())
                        .as("check ficheFormation contenty type")
                        .isEqualTo(actual.getFicheFormationContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormationUpdatableRelationshipsEquals(Formation expected, Formation actual) {
        assertThat(expected)
            .as("Verify Formation relationships")
            .satisfies(e -> assertThat(e.getEtablissements()).as("check etablissements").isEqualTo(actual.getEtablissements()));
    }
}
